#!/usr/bin/env bash
set -euo pipefail

REPO_RAW="https://raw.githubusercontent.com/rainbowgag/VPS-Traffic-Monitoring/main"

AGENT_APP="vps-traffic-monitor"
AGENT_INSTALL_DIR="/opt/${AGENT_APP}"
AGENT_CONFIG_DIR="/etc/${AGENT_APP}"
AGENT_DATA_DIR="/var/lib/${AGENT_APP}"
AGENT_SERVICE="/etc/systemd/system/${AGENT_APP}.service"
AGENT_DEFAULT_PORT="8899"

HUB_APP="vps-traffic-hub"
HUB_INSTALL_DIR="/opt/${HUB_APP}"
HUB_CONFIG_DIR="/etc/${HUB_APP}"
HUB_DATA_DIR="/var/lib/${HUB_APP}"
HUB_SERVICE="/etc/systemd/system/${HUB_APP}.service"
HUB_DEFAULT_PORT="8898"

ROLE="agent"
ACTION=""
PORT="${AGENT_DEFAULT_PORT}"
HUB_PORT="${HUB_DEFAULT_PORT}"
RESET_DAY="1"
INTERFACES=""
ADMIN_USER=""
ADMIN_PASSWORD=""
HUB_URL=""
AGENT_TOKEN=""
REPORT_INTERVAL=""
SMTP_ENABLED="0"
SMTP_HOST=""
SMTP_PORT="587"
SMTP_USERNAME=""
SMTP_PASSWORD=""
SMTP_FROM=""
SMTP_TO=""
SMTP_STARTTLS="1"
PURGE="0"
INTERACTIVE="1"

usage() {
  cat <<EOF
Usage: bash install.sh [options]

Without options, this script opens an interactive agent menu:
  1. Install traffic monitor (agent)
  2. Update traffic monitor (agent)
  3. Uninstall traffic monitor (agent)

Options:
  --action install|update|uninstall
  --role agent|hub            What to install, default: agent
  --port PORT                 Agent panel port, default: ${AGENT_DEFAULT_PORT}
  --hub-port PORT             Hub dashboard port, default: ${HUB_DEFAULT_PORT}
  --reset-day DAY             Agent monthly reset day 1-31, default: 1
  --interfaces LIST           Agent interfaces, e.g. eth0,ens3. Empty means auto.
  --admin-user USER           Admin login username, default: admin
  --admin-password PASS       Admin login password. Empty keeps existing or auto-generates.
  --hub-url URL               Agent: Hub URL, e.g. http://YOUR_HUB_IP:8898
  --agent-token TOKEN         Agent: token from Hub (generated by hub.py --add-node)
  --report-interval SECONDS   Agent: report interval, default 60
  --smtp-enabled 1|0          Hub: enable SMTP alerts
  --smtp-host HOST            Hub: SMTP host
  --smtp-port PORT            Hub: SMTP port, default 587
  --smtp-username USER        Hub: SMTP username
  --smtp-password PASS        Hub: SMTP password / authorization code
  --smtp-from EMAIL           Hub: from address
  --smtp-to EMAILS            Hub: comma-separated recipients
  --smtp-starttls 1|0         Hub: use STARTTLS, default 1
  --purge                     With uninstall, also remove config and databases
  --yes                       Non-interactive mode, use provided/default values
  --help                      Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --action)
      ACTION="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --role)
      ROLE="${2:-agent}"; INTERACTIVE="0"; shift 2 ;;
    --port)
      PORT="${2:-}"; HUB_PORT="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --hub-port)
      HUB_PORT="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --reset-day)
      RESET_DAY="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --interfaces)
      INTERFACES="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --admin-user)
      ADMIN_USER="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --admin-password)
      ADMIN_PASSWORD="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --hub-url)
      HUB_URL="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --agent-token)
      AGENT_TOKEN="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --report-interval)
      REPORT_INTERVAL="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --smtp-enabled)
      SMTP_ENABLED="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --smtp-host)
      SMTP_HOST="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --smtp-port)
      SMTP_PORT="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --smtp-username)
      SMTP_USERNAME="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --smtp-password)
      SMTP_PASSWORD="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --smtp-from)
      SMTP_FROM="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --smtp-to)
      SMTP_TO="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --smtp-starttls)
      SMTP_STARTTLS="${2:-}"; INTERACTIVE="0"; shift 2 ;;
    --purge)
      PURGE="1"; INTERACTIVE="0"; shift ;;
    --yes|-y)
      INTERACTIVE="0"; shift ;;
    --help|-h)
      usage; exit 0 ;;
    *)
      echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

need_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "Please run as root: sudo bash install.sh" >&2
    exit 1
  fi
}

check_number() {
  local value="$1" name="$2" min="$3" max="$4"
  if ! [[ "${value}" =~ ^[0-9]+$ ]] || (( value < min || value > max )); then
    echo "${name} must be a number from ${min} to ${max}" >&2
    exit 1
  fi
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

install_python_hint() {
  if command -v apt-get >/dev/null 2>&1; then
    echo "Install it with: apt-get update && apt-get install -y python3 curl"
  elif command -v dnf >/dev/null 2>&1; then
    echo "Install it with: dnf install -y python3 curl"
  elif command -v yum >/dev/null 2>&1; then
    echo "Install it with: yum install -y python3 curl"
  elif command -v apk >/dev/null 2>&1; then
    echo "Install it with: apk add python3 curl"
  fi
}

prompt_menu() {
  echo
  echo "VPS Traffic Monitoring (Agent)"
  echo "1. Install traffic monitor"
  echo "2. Update traffic monitor"
  echo "3. Uninstall traffic monitor"
  echo
  read -r -p "Choose an option [1-3]: " choice
  choice="$(printf '%s' "${choice}" | tr -cd '0-9')"
  choice="${choice:-1}"
  case "${choice}" in
    1) ACTION="install" ;;
    2) ACTION="update" ;;
    3) ACTION="uninstall" ;;
    *) echo "Invalid option." >&2; exit 1 ;;
  esac
}

prompt_install_config() {
  local input=""
  read -r -p "Web panel port [${AGENT_DEFAULT_PORT}]: " input
  PORT="${input:-${AGENT_DEFAULT_PORT}}"
  read -r -p "Monthly reset day 1-31 [1]: " input
  RESET_DAY="${input:-1}"
  read -r -p "Interfaces to count, for example eth0,ens3. Press Enter for auto: " input
  INTERFACES="${input:-__AUTO__}"
  read -r -p "Admin username [admin]: " input
  ADMIN_USER="${input:-admin}"
  read -r -p "Admin password [press Enter to keep existing or auto-generate]: " input
  ADMIN_PASSWORD="${input:-}"
}

prompt_uninstall_config() {
  local input=""
  read -r -p "Also remove config and traffic database? [y/N]: " input
  case "${input}" in
    y|Y|yes|YES) PURGE="1" ;;
    *) PURGE="0" ;;
  esac
}

check_linux_runtime() {
  if [[ "$(uname -s)" != "Linux" ]]; then
    echo "This script only supports Linux VPS systems." >&2
    exit 1
  fi
  require_cmd systemctl
}

install_agent() {
  local label="$1"
  check_number "${PORT}" "port" 1 65535
  check_number "${RESET_DAY}" "reset day" 1 31

  if [[ ! -r /proc/net/dev ]]; then
    echo "/proc/net/dev is not readable. Traffic counters are unavailable." >&2
    exit 1
  fi

  if ! command -v python3 >/dev/null 2>&1; then
    echo "python3 is required." >&2
    install_python_hint
    exit 1
  fi
  if ! command -v curl >/dev/null 2>&1; then
    echo "curl is required." >&2
    install_python_hint
    exit 1
  fi

  echo "Preparing ${AGENT_APP} ${label}..."
  mkdir -p "${AGENT_INSTALL_DIR}" "${AGENT_CONFIG_DIR}" "${AGENT_DATA_DIR}"

  TMP_FILE="$(mktemp)"
  trap 'rm -f "${TMP_FILE}"' EXIT

  if [[ -f "./monitor.py" ]]; then
    cp "./monitor.py" "${TMP_FILE}"
  else
    curl -fsSL "${REPO_RAW}/monitor.py" -o "${TMP_FILE}"
  fi

  python3 -m py_compile "${TMP_FILE}"
  install -m 0755 "${TMP_FILE}" "${AGENT_INSTALL_DIR}/monitor.py"

  echo "Writing agent configuration..."
  python3 - "${AGENT_CONFIG_DIR}/config.json" "${PORT}" "${RESET_DAY}" "${INTERFACES}" "${ADMIN_USER}" "${ADMIN_PASSWORD}" "${HUB_URL}" "${AGENT_TOKEN}" "${REPORT_INTERVAL}" <<'PY'
import base64
import hashlib
import json
import os
import secrets
import sys

path, port, reset_day, interfaces, admin_user, admin_password, hub_url, agent_token, report_interval = sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), sys.argv[4], sys.argv[5], sys.argv[6], sys.argv[7], sys.argv[8], sys.argv[9]

def hash_password(password, salt=None):
    salt = salt or secrets.token_hex(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt.encode("utf-8"), 120000)
    return "pbkdf2_sha256${}${}".format(salt, base64.b64encode(digest).decode("ascii"))

config = {
    "host": "0.0.0.0",
    "port": port,
    "reset_day": reset_day,
    "interfaces": [],
    "exclude_interfaces": ["lo", "docker*", "br-*", "veth*", "virbr*", "zt*", "tailscale*", "wg*"],
    "sample_interval": 5,
    "database": "/var/lib/vps-traffic-monitor/traffic.db",
    "admin_user": "admin",
    "admin_password_hash": "",
    "secret_key": secrets.token_hex(32),
    "hub_url": "",
    "agent_token": "",
    "report_interval": 60,
}
if os.path.exists(path):
    with open(path, "r", encoding="utf-8") as fh:
        old = json.load(fh)
    config.update(old)
config["port"] = port
config["reset_day"] = reset_day
if hub_url.strip():
    config["hub_url"] = hub_url.strip()
if agent_token.strip():
    config["agent_token"] = agent_token.strip()
if report_interval.strip():
    config["report_interval"] = max(10, int(report_interval))
config.setdefault("hub_url", "")
config.setdefault("agent_token", "")
config.setdefault("report_interval", 60)
if admin_user.strip():
    config["admin_user"] = admin_user.strip()
if admin_password:
    config["admin_password_hash"] = hash_password(admin_password)
elif not config.get("admin_password_hash"):
    generated = secrets.token_urlsafe(12)
    config["admin_password_hash"] = hash_password(generated)
    print("Generated admin password: {}".format(generated))
if not config.get("secret_key"):
    config["secret_key"] = secrets.token_hex(32)
if interfaces.strip() == "__AUTO__":
    config["interfaces"] = []
elif interfaces.strip():
    config["interfaces"] = [x.strip() for x in interfaces.split(",") if x.strip()]
os.makedirs(os.path.dirname(path), exist_ok=True)
tmp = f"{path}.tmp"
with open(tmp, "w", encoding="utf-8") as fh:
    json.dump(config, fh, ensure_ascii=False, indent=2)
os.replace(tmp, path)
PY

  cat > "${AGENT_SERVICE}" <<EOF
[Unit]
Description=VPS Traffic Monitoring Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/env python3 ${AGENT_INSTALL_DIR}/monitor.py --config ${AGENT_CONFIG_DIR}/config.json
Restart=always
RestartSec=3
User=root
WorkingDirectory=${AGENT_INSTALL_DIR}

[Install]
WantedBy=multi-user.target
EOF

  systemctl stop "${AGENT_APP}" >/dev/null 2>&1 || true
  systemctl daemon-reload
  systemctl enable "${AGENT_APP}" >/dev/null
  systemctl restart "${AGENT_APP}"

  sleep 1
  if ! systemctl is-active --quiet "${AGENT_APP}"; then
    systemctl status "${AGENT_APP}" --no-pager || true
    echo "Agent service failed to start." >&2
    exit 1
  fi

  PUBLIC_IP="$(curl -fsS --max-time 3 https://api.ipify.org 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}')"
  echo
  echo "VPS Traffic Monitoring agent ${label} successfully."
  echo "Local panel: http://${PUBLIC_IP:-YOUR_VPS_IP}:${PORT}"
  echo "Config: ${AGENT_CONFIG_DIR}/config.json"
  echo "Data: ${AGENT_DATA_DIR}/traffic.db"
}

install_hub() {
  local label="$1"
  check_number "${HUB_PORT}" "hub port" 1 65535

  if ! command -v python3 >/dev/null 2>&1; then
    echo "python3 is required." >&2
    install_python_hint
    exit 1
  fi
  if ! command -v curl >/dev/null 2>&1; then
    echo "curl is required." >&2
    install_python_hint
    exit 1
  fi

  echo "Preparing ${HUB_APP} ${label}..."
  mkdir -p "${HUB_INSTALL_DIR}" "${HUB_CONFIG_DIR}" "${HUB_DATA_DIR}"

  TMP_HUB="$(mktemp)"
  trap 'rm -f "${TMP_HUB}"' EXIT

  if [[ -f "./hub.py" ]]; then
    cp "./hub.py" "${TMP_HUB}"
  else
    curl -fsSL "${REPO_RAW}/hub.py" -o "${TMP_HUB}"
  fi

  python3 -m py_compile "${TMP_HUB}"
  install -m 0755 "${TMP_HUB}" "${HUB_INSTALL_DIR}/hub.py"

  echo "Writing hub configuration..."
  python3 - "${HUB_CONFIG_DIR}/config.json" "${HUB_PORT}" "${ADMIN_USER}" "${ADMIN_PASSWORD}" "${SMTP_ENABLED}" "${SMTP_HOST}" "${SMTP_PORT}" "${SMTP_USERNAME}" "${SMTP_PASSWORD}" "${SMTP_FROM}" "${SMTP_TO}" "${SMTP_STARTTLS}" <<'PY'
import base64
import hashlib
import json
import os
import secrets
import sys

path, port, admin_user, admin_password, smtp_enabled, smtp_host, smtp_port, smtp_username, smtp_password, smtp_from, smtp_to, smtp_starttls = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6], sys.argv[7], sys.argv[8], sys.argv[9], sys.argv[10], sys.argv[11], sys.argv[12]

def hash_password(password, salt=None):
    salt = salt or secrets.token_hex(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt.encode("utf-8"), 120000)
    return "pbkdf2_sha256${}${}".format(salt, base64.b64encode(digest).decode("ascii"))

def truthy(value):
    return str(value).lower() in ("1", "true", "yes", "on")

config = {
    "host": "0.0.0.0",
    "port": port,
    "database": "/var/lib/vps-traffic-hub/hub.db",
    "admin_user": "admin",
    "admin_password_hash": "",
    "secret_key": secrets.token_hex(32),
    "default_tz_offset_minutes": 480,
    "smtp": {
        "enabled": truthy(smtp_enabled),
        "host": smtp_host,
        "port": int(smtp_port or 587),
        "username": smtp_username,
        "password": smtp_password,
        "from_addr": smtp_from,
        "to_addrs": [x.strip() for x in smtp_to.split(",") if x.strip()],
        "use_ssl": False,
        "use_starttls": truthy(smtp_starttls) if smtp_starttls != "" else True,
    },
    "alert_cooldown_hours": 24,
    "recovery_email_enabled": True,
    "dashboard_url": "",
    "check_interval": 300,
}
if os.path.exists(path):
    with open(path, "r", encoding="utf-8") as fh:
        old = json.load(fh)
    config.update(old)
    config["port"] = port
    smtp = config.setdefault("smtp", {})
    if smtp_enabled != "":
        smtp["enabled"] = truthy(smtp_enabled)
    if smtp_host:
        smtp["host"] = smtp_host
    if smtp_port:
        smtp["port"] = int(smtp_port)
    if smtp_username:
        smtp["username"] = smtp_username
    if smtp_password:
        smtp["password"] = smtp_password
    if smtp_from:
        smtp["from_addr"] = smtp_from
    if smtp_to:
        smtp["to_addrs"] = [x.strip() for x in smtp_to.split(",") if x.strip()]
    if smtp_starttls != "":
        smtp["use_starttls"] = truthy(smtp_starttls)
    smtp.setdefault("use_ssl", False)
if admin_user.strip():
    config["admin_user"] = admin_user.strip()
if admin_password:
    config["admin_password_hash"] = hash_password(admin_password)
elif not config.get("admin_password_hash"):
    generated = secrets.token_urlsafe(12)
    config["admin_password_hash"] = hash_password(generated)
    print("Generated admin password: {}".format(generated))
if not config.get("secret_key"):
    config["secret_key"] = secrets.token_hex(32)
os.makedirs(os.path.dirname(path), exist_ok=True)
tmp = f"{path}.tmp"
with open(tmp, "w", encoding="utf-8") as fh:
    json.dump(config, fh, ensure_ascii=False, indent=2)
os.replace(tmp, path)
PY

  cat > "${HUB_SERVICE}" <<EOF
[Unit]
Description=VPS Traffic Hub
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/env python3 ${HUB_INSTALL_DIR}/hub.py --config ${HUB_CONFIG_DIR}/config.json
Restart=always
RestartSec=3
User=root
WorkingDirectory=${HUB_INSTALL_DIR}

[Install]
WantedBy=multi-user.target
EOF

  systemctl stop "${HUB_APP}" >/dev/null 2>&1 || true
  systemctl daemon-reload
  systemctl enable "${HUB_APP}" >/dev/null
  systemctl restart "${HUB_APP}"

  sleep 1
  if ! systemctl is-active --quiet "${HUB_APP}"; then
    systemctl status "${HUB_APP}" --no-pager || true
    echo "Hub service failed to start." >&2
    exit 1
  fi

  PUBLIC_IP="$(curl -fsS --max-time 3 https://api.ipify.org 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}')"
  echo
  echo "VPS Traffic Hub ${label} successfully."
  echo "Dashboard: http://${PUBLIC_IP:-YOUR_VPS_IP}:${HUB_PORT}"
  echo "Config: ${HUB_CONFIG_DIR}/config.json"
  echo "Data: ${HUB_DATA_DIR}/hub.db"
  echo
  echo "Add a node and get its token:"
  echo "  python3 ${HUB_INSTALL_DIR}/hub.py --config ${HUB_CONFIG_DIR}/config.json --add-node 节点名称"
}

uninstall_agent() {
  if command -v systemctl >/dev/null 2>&1; then
    systemctl stop "${AGENT_APP}" >/dev/null 2>&1 || true
    systemctl disable "${AGENT_APP}" >/dev/null 2>&1 || true
  fi
  rm -f "${AGENT_SERVICE}"
  if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload
    systemctl reset-failed "${AGENT_APP}" >/dev/null 2>&1 || true
  fi
  rm -rf "${AGENT_INSTALL_DIR}"
  if [[ "${PURGE}" == "1" ]]; then
    rm -rf "${AGENT_CONFIG_DIR}" "${AGENT_DATA_DIR}"
    echo "Agent uninstalled. Config and data were removed."
  else
    echo "Agent uninstalled. Config and data were kept:"
    echo "  ${AGENT_CONFIG_DIR}"
    echo "  ${AGENT_DATA_DIR}"
  fi
}

uninstall_hub() {
  if command -v systemctl >/dev/null 2>&1; then
    systemctl stop "${HUB_APP}" >/dev/null 2>&1 || true
    systemctl disable "${HUB_APP}" >/dev/null 2>&1 || true
  fi
  rm -f "${HUB_SERVICE}"
  if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload
    systemctl reset-failed "${HUB_APP}" >/dev/null 2>&1 || true
  fi
  rm -rf "${HUB_INSTALL_DIR}"
  if [[ "${PURGE}" == "1" ]]; then
    rm -rf "${HUB_CONFIG_DIR}" "${HUB_DATA_DIR}"
    echo "Hub uninstalled. Config and data were removed."
  else
    echo "Hub uninstalled. Config and data were kept:"
    echo "  ${HUB_CONFIG_DIR}"
    echo "  ${HUB_DATA_DIR}"
  fi
}

need_root

if [[ "${INTERACTIVE}" == "1" ]]; then
  prompt_menu
  if [[ "${ACTION}" == "install" || "${ACTION}" == "update" ]]; then
    prompt_install_config
  elif [[ "${ACTION}" == "uninstall" ]]; then
    prompt_uninstall_config
  fi
fi

case "${ACTION}" in
  1)
    ACTION="install"
    check_linux_runtime
    install_agent "installed"
    ;;
  2)
    ACTION="update"
    check_linux_runtime
    install_agent "updated"
    ;;
  3)
    ACTION="uninstall"
    check_linux_runtime
    uninstall_agent
    ;;
  install)
    check_linux_runtime
    if [[ "${ROLE}" == "hub" ]]; then
      install_hub "installed"
    else
      install_agent "installed"
    fi
    ;;
  update)
    check_linux_runtime
    if [[ "${ROLE}" == "hub" ]]; then
      install_hub "updated"
    else
      install_agent "updated"
    fi
    ;;
  uninstall)
    check_linux_runtime
    if [[ "${ROLE}" == "hub" ]]; then
      uninstall_hub
    else
      uninstall_agent
    fi
    ;;
  "")
    echo "No action selected." >&2
    usage
    exit 1
    ;;
  *)
    echo "Invalid action: ${ACTION}" >&2
    usage
    exit 1
    ;;
esac
